FROM python:3.11-slim

WORKDIR /dashboard

COPY requirements-dashboard.txt .

RUN pip install --no-cache-dir -r requirements-dashboard.txt

COPY dashboard ./dashboard

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
