services:

  telecom-api:
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: telecom-api

    ports:
      - "8000:8000"

  telecom-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard

    container_name: telecom-dashboard

    ports:
      - "8501:8501"

    depends_on:
      - telecom-api