name: CI Churn Project

on:
  push:
    branches: [ "master" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-api.txt -r requirements-dashboard.txt pytest httpx

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Run Pytest
        run: |
          pytest

      - name: Build API Docker image
        run: |
          docker build -f Dockerfile.api -t telecom-api .

      - name: Build Dashboard Docker image
        run: |
          docker build -f Dockerfile.dashboard -t telecom-dashboard .