name: CI Churn Project

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt
          pip install pytest httpx

      - run: pytest -v